eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://eureka7001.com:5060/eureka/
    instance:
        hostname: eureka7001.com
server:
    port: 7001
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dda?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: sun
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
