server:
  port: 7005
  application:
    name: service-gateway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: provide
          uri: lb://provide
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
  datasource:
    url: jdbc:mysql://localhost:3306/dda?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: sun
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
