server:
  port: 7005

spring:
  cloud:
    gateway:
      discovery:
        locator:
            enabled: true
            lower-case-service-id: true
      routes:
      - id: serviceprovide
        uri: lb://provide
        predicates:
        - Path=/serviceprovide/**
        filters:
        - StripPrefix=1
        - id: baidu
            uri: http://www.baidu.com
            predicates:
              - Path=/baidu
            filters:
              - StripPrefix=1
  datasource:
    url: jdbc:mysql://localhost:3306/dda?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: sun
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: gateway
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
